### ISSUE TITLE
Support for dbt 1.5

### ISSUE THREAD

**Issue by connor-charles** [autotraderuk/dbt-dry-run#38]
dbt v1.5 has been released. Placeholder issue to update integration tests to run against the new version and fix any issues.

Looks like `model contracts` tries to replicate what `dry_run.check_columns` does but doesn't work for all incremental configurations (Only `append_new_columns`?) So we will keep this feature in the dry runner for now.

**Comment by connor-charles** [comment]
`dbt-dry-run` will currently raise an ImportError when run with v1.5:

```
Traceback (most recent call last):
  File "/project/.meltano/utilities/dbt-dry-run/venv/bin/dbt-dry-run", line 5, in <module>
    from dbt_dry_run.__main__ import main
  File "/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 1, in <module>
    from dbt_dry_run.cli import app
  File "/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 5, in <module>
    from dbt.flags import DEFAULT_PROFILES_DIR
ImportError: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags' (/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt/flags.py)
```
