### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags'

### ISSUE THREAD

**Issue by SBurwash** [autotraderuk/dbt-dry-run#39]
Getting this error when running our dry-run package. Is this normal? How can I fix this?

Full trace from our meltano utility:
```
Traceback (most recent call last):
  File "/project/.meltano/utilities/dbt-dry-run/venv/bin/dbt-dry-run", line 5, in <module>
    from dbt_dry_run.__main__ import main
  File "/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 1, in <module>
    from dbt_dry_run.cli import app
  File "/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 5, in <module>
    from dbt.flags import DEFAULT_PROFILES_DIR
ImportError: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags' (/project/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt/flags.py)
```

**Comment by connor-charles** [comment]
Hey @SBurwash,

Thanks for reporting!

This is due to the recent dbt release (#38). I am currently working on a release to patch this.

**Comment by SBurwash** [comment]
@connor-charles awesome thanks!
