### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by SBurwash** [autotraderuk/dbt-dry-run#41]
Hey everyone,

I am getting this error when running `dbt-dry-run`

From the larger context:

```
2023-05-23T15:20:52.902022Z [info     ] Environment 'prod' is active
Using project-dir at `/home/runner/work/meltano/meltano/transform`...
Using profile.yml at `/home/runner/work/meltano/meltano/transform/profiles/bigquery`...
Traceback (most recent call last):
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/bin/dbt-dry-run", line 5, in <module>
    from dbt_dry_run.__main__ import main
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 1, in <module>
    from dbt_dry_run.cli import app
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 8, in <module>
    from dbt_dry_run.adapter.service import DbtArgs, ProjectService
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/adapter/service.py", line 13, in <module>
    from dbt_dry_run.models import Manifest
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/models/__init__.py", line 1, in <module>
    from .manifest import Macro, Manifest, Node, NodeConfig, NodeDependsOn, OnSchemaChange
  File "/home/runner/work/meltano/meltano/.meltano/utilities/dbt-dry-run/venv/lib/python3.8/site-packages/dbt_dry_run/models/manifest.py", line 28, in <module>
    class PartitionBy(BaseModel):
  File "pydantic/main.py", line [19](https://github.com/potloc/meltano/actions/runs/5059083507/jobs/9080108265#step:13:20)7, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Would this be user error? How may I solve this?

**Comment by ccharlesgb** [comment]
Hey,

This is probably a compatibility issue between versions. We should really change the requirements for the package to be the correct version of dbt. The compatibility for the last two dbt versions is:

dbt-dry-run -> dbt
0.6.7 -> 1.5
0.6.4, 0.6.5, 0.6.6 -> 1.4

**Comment by ccharlesgb** [comment]
Did some reading on the error. Does this workaround help?

https://github.com/explosion/spaCy/issues/12659

**Comment by SBurwash** [comment]
Hey @ccharlesgb , seems the error fixed itself once we redeployed ;) thanks for looking into it though! Will be closing the issue
