### ISSUE TITLE
Issues/Bugs on initial look

### ISSUE THREAD

**Issue by rwillard** [autotraderuk/dbt-dry-run#7]
First of all, thank you for opening up this tool, my team is excited to utilize it. We've been utilizing dbt for a few months now, and additional testing is great :)

Two issues that came up while setting up.
First, `dataset` & `schema` seem to be used interchangeably for bigquery profiles. We had dataset, would prefer to keep as dataset, but switched to resolve
```
root@ab14a47c8eeb:/src/app# dbt-dry-run cdm-editor --profiles-dir . --manifest-path target/manifest.json
Traceback (most recent call last):
  File "/usr/local/bin/dbt-dry-run", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 5, in main
    exit(cli.run())
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 73, in run
    profiles = read_profiles(parsed_args.profiles_dir)
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 66, in read_profiles
    all_profiles[name] = Profile(**profile)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Profile
outputs -> demo -> schema
  field required (type=value_error.missing)
  ```
  Second issue, dbt-dry-run didn't work with [as_number](https://docs.getdbt.com/reference/dbt-jinja-functions/as_number)  in profiles. Work around of hard coding for now.
  ```root@ab14a47c8eeb:/src/app# dbt-dry-run cdm-editor --profiles-dir . --manifest-path target/manifest.json
Traceback (most recent call last):
  File "/usr/local/bin/dbt-dry-run", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 5, in main
    exit(cli.run())
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 73, in run
    profiles = read_profiles(parsed_args.profiles_dir)
  File "/usr/local/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 61, in read_profiles
    template = template_env.get_template(PROFILE_FILENAME)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "./profiles.yml", line 14, in template
    maximum_bytes_billed: "{{ env_var('DBT_MAXIMUM_BYTES_BILLED', '250000000000') | as_number }}"
jinja2.exceptions.TemplateAssertionError: no filter named 'as_number'
```
Are these to be expected? I can take a stab at opening a PR to fix at least the first issue :)

**Comment by connor-charles** [comment]
Hi @rwillard,

Thanks for raising an issue! I have raised a PR to fix these. Hoping to get that fix out with the release of snapshot support.

#9
