### ISSUE TITLE
ModuleNotFoundError: No module named 'dbt.contracts.connection'

### ISSUE THREAD

**Issue by SBurwash** [autotraderuk/dbt-dry-run#75]
Good day,

I recently upgrade to `dbt-core==1.8.3` & `dbt-bigquery==1.8.2`, and I am suddenly getting the following error when running `dbt-dry-run` in CI:

```
ModuleNotFoundError: No module named 'dbt.contracts.connection'
```

Full log output:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/dbt-dry-run", line 5, in <module>
    from dbt_dry_run.__main__ import main
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/dbt_dry_run/__main__.py", line 1, in <module>
    from dbt_dry_run.cli import app
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/dbt_dry_run/cli.py", line 8, in <module>
    from dbt_dry_run.adapter.service import DbtArgs, ProjectService
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/dbt_dry_run/adapter/service.py", line 9, in <module>
    from dbt.contracts.connection import Connection
ModuleNotFoundError: No module named 'dbt.contracts.connection'
```

Would you have any advice on how to resolve this?

Thanks 🙏

**Comment by ccharlesgb** [comment]
If you upgrade `dbt-dry-run` then this should fix it 👍
